[package]
name = "melevo-core"
version = "0.1.0"
edition = "2024"

[lib]
name = "core"
path = "src/lib.rs"

[dependencies]
melevo-render = { path = "../melevo-render" }
log.workspace = true
winit.workspace = true