[package]
name = "melevo-macro"
version = "0.1.0"
edition = "2024"

[lib]
name = "macros"
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
