[workspace]
members = [
	"melevo",
	"melevo-core",
	"melevo-ecs",
	"melevo-physic",
	"melevo-render",
	"melevo-vulkan",
]

[workspace.dependencies]
winit = { version = "0.30.8", features = ["rwh_05"] }
log = "0.4.27"