[workspace]
members = [
	"melevo",
	"melevo-core",
	"melevo-ecs",
	"melevo-physic",
	"melevo-render", "melevo-utils",
	"melevo-vulkan",
]

[workspace.dependencies]
log = "0.4.27"
versions = "7.0.0"
winit = { version = "0.30.8", features = ["rwh_05"] }
