[package]
name = "melevo-render"
version = "0.1.0"
edition = "2024"

[lib]
name = "render"
path = "src/lib.rs"

[dependencies]
melevo-utils = { path = "../melevo-utils" }
melevo-vulkan = { path = "../melevo-vulkan" }
log.workspace = true
winit.workspace = true
versions.workspace = true